
services:
  api:
    image: kimuntu/fruits360-mlops:latest
    container_name: fruits360-api
    working_dir: /app
    volumes:
      - .:/app
    command: uvicorn API.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  streamlit:
    image: kimuntu/fruits360-mlops:latest
    container_name: fruits360-streamlit
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8000
    command: streamlit run app_streamlit.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api 